### PR TITLE
Fix "companion unloaded"

### PR DESCRIPTION
**Pull request by Beat-YT**
Fix the "Compagnion Unloaded" issue that is pretty annoying. 

Simply by waiting 3 second before installing the app.
image

I also added checks since this issue only apply to real devices
image

### CODE REVIEW

**Comment by Beat-YT** [comment]
@Hexxeh

**Comment by Hexxeh** [comment]
I'm not sure a 3s delay on every single app launch is the right solution here, we'd have to investigate why this happens.

**Comment by Beat-YT** [comment]
I added a 3sec timeout since it say "unloading companion in 3 sec

**Comment by Beat-YT** [comment]
But it looks like it's.waiting for the app to start to unload the companion

**Pull request closed without merging**
